version: '3.4'

networks:
  backend:

services:
  ft-ai:
    image: ${DOCKER_REGISTRY-}ftai
    build:
      context: .
      dockerfile: FT - AI/Dockerfile
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ft-alimentos:
    image: ${DOCKER_REGISTRY-}ftalimentos
    build:
      context: .
      dockerfile: FT - Alimentos/Dockerfile
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"


  ft-base:
    image: ${DOCKER_REGISTRY-}ftbase
    build:
      context: .
      dockerfile: FT - Base/Dockerfile
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

